---
title: "Pedagogika - základní přehled"
output: html_document
---

```{r, echo=FALSE}
data_ped <- read.csv("./data/data_ped.csv", stringsAsFactors=FALSE)

```


## Celkové počty publikací v oboru Pedagogika:

```{r, echo=FALSE}
barplot(table(data_ped$ROKUPLEFF), main="Celkový počet publikací dle jednotlivých let")

table(data_ped$ROKUPLEFF)
```

- dle druhu výsledku:

```{r, echo=FALSE}
barplot(sort(table(data_ped$DRUHODKOD), decreasing = TRUE), 
        main="Celkový počet publikací dle druhu výsledku")

sort(table(data_ped$DRUHODKOD), decreasing = TRUE)
```

- dle jazyka výsledku:

```{r, echo=FALSE}
pie_chart <- sort(table(data_ped$VYSJAZKOD), decreasing = TRUE)

slices <- c(pie_chart[1], pie_chart[2], sum(pie_chart[3:length(pie_chart)]))
lbls <- c("Čeština", "Angličtina", "Ostatní")
pie(slices, labels = lbls, col=rainbow(length(lbls)), main="Počty publikací dle jazyka")

pie_chart
```


**Dle institucí (vypíše 20 institucí s nejvyšším počtem publikací)**

```{r, echo=FALSE}
instituce <- head(sort(table(data_ped$INSNAZPKL), decreasing = TRUE), n = 20)
instituce
```


**Dle fakult tří  hlavních univerzit:**
 
```{r, echo=FALSE}
mu <- data_ped[data_ped$INSNAZPKL == "Masarykova univerzita", ]

pie_chart <- sort(table(mu$ORJNAZPKL), decreasing = TRUE)

slices <- c(pie_chart[1], pie_chart[2], sum(pie_chart[3:length(pie_chart)]))
lbls <- c("Pedagogická fakulta", "Filozofická fakulta", "Ostatní")
pie(slices, labels = lbls, col=rainbow(length(lbls)), main="Počet publikací dle fakult Masarykovy univerzity")

pie_chart

```


```{r, echo=FALSE}
upol <- data_ped[data_ped$INSNAZPKL == "Univerzita Palackého v Olomouci", ]

pie_chart <- sort(table(upol$ORJNAZPKL), decreasing = TRUE)

slices <- c(pie_chart[1], pie_chart[2], sum(pie_chart[3:length(pie_chart)]))
lbls <- c("Pedagogická fakulta", "Fakulta tělesné kultury", "Ostatní")
pie(slices, labels = lbls, col=rainbow(length(lbls)), main="Počet publikací dle fakult Univerzity Palackého v Olomouci")

pie_chart

```


```{r, echo=FALSE}
uk <- data_ped[data_ped$INSNAZPKL == "Univerzita Karlova v Praze", ]

pie_chart <- sort(table(uk$ORJNAZPKL), decreasing = TRUE)

slices <- c(pie_chart[1], pie_chart[2], pie_chart[3], pie_chart[4], pie_chart[5], sum(pie_chart[6:length(pie_chart)]))
lbls <- c("Pedagogická fakulta", "Přírodovědecká fakulta", "Fakulta tělesné výchovy a sportu", "Filozofická fakulta", "Matematicko-fyzikální fakulta", "Ostatní")
pie(slices, labels = lbls, col=rainbow(length(lbls)), main="Počet publikací dle fakult Univerzity Karlovy v Praze")

pie_chart

```

